### ISSUE TITLE
Quadratization

### ISSUE THREAD

**Issue by AndradeTiago** [psrenergy/ToQUBO.jl#20]
Currently, the reduce_degree is done inside each toqubo_constraint! call.

If it was done after every constraint is known, it could leverage in the knowledge of how many times each product appears in the model.

**Comment by bernalde** [comment]
This trick of aux-less quadratization methods is mapping the energy function to something that has the same minima of lower degree (not a trivial task). I think that the first approach in https://arxiv.org/abs/1508.04816 should be the easiest one to follow and implement
Moreover, this repo https://github.com/HPQC-LABS/QuadratizationCode has already a myriad of code (somewhat disorganized) for the quadratizations. 
On a slightly related note, I was really surprised when I saw you had already implemented the domain wall approach! It seems to work like a charm in practice https://arxiv.org/abs/2108.12004

**Comment by AndradeTiago** [comment]
Very interesting. I was worried that it could introduce new inputs with the minimum value, this could lead to false negatives in the constraints violation. However, this is not the case as the papers state this:
"Any input that minimizes the original objective function also minimizes the new one, and no new inputs can minimize the objective function"

I'll read more carefully to understand the method.
