### ISSUE TITLE
Incorrect values on multiple results

### ISSUE THREAD

**Issue by pedromxavier** [psrenergy/ToQUBO.jl#35]
As described in [discourse](https://discourse.julialang.org/t/toqubo-jl-potential-issue/78955), there appears to be an issue when retrieving multiple results.

**Comment by bernalde** [comment]
Is this a private discourse?

**Comment by joaquimg** [comment]
Yes, the user messaged me and @pedromxavier .

**Comment by YummyPampers2** [comment]
Hello -- has there been any progress on this issue? 
Wondering if it is a simple fix or you could provide
some resources for me to explore a solution?

**Comment by pedromxavier** [comment]
This issue has nothing to do with this package, it's Anneal's fault.
