### ISSUE TITLE
Non-trivial conversions -- Primer 

### ISSUE THREAD

**Issue by YummyPampers2** [psrenergy/ToQUBO.jl#36]
Hello @pedromxavier, @joaquimg, 
& @bernalde: 

I am attempting to convert two 
non-trivial functions from Python 
to Julia:

```
qubovert.utils.qubo_to_quso
qubovert.utils.quso_to_qubo
```

What elements of the above functions 
would one unit test in Python? Is it 
necessary to use Python, or could one
directly unit test with Julia? If so, would
you mind sharing your approach here? 

Thank you,

**Comment by pedromxavier** [comment]
IMO when using Python functions in Julia, it is nice to use [PythonCall](https://github.com/cjdoris/PythonCall.jl).
Also, this kind of topic doesn't has much to do with this project, so better posting it on discourse.
